// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO
    databases (
        id,
        title,
        type,
        host,
        port,
        username,
        password,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, title, type, host, port, username, password, created_at, updated_at, deleted_at
`

type CreateDatabaseParams struct {
	ID        string
	Title     string
	Type      string
	Host      string
	Port      int32
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE id = $1
`

func (q *Queries) DeleteDatabase(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, title, type, host, port, username, password, created_at, updated_at, deleted_at FROM databases WHERE id = $1
`

func (q *Queries) GetDatabase(ctx context.Context, id string) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
